(source gnu)
(source melpa)

;(depends-on "ac-dabbrev")
(depends-on "anzu")
(depends-on "auto-complete")
(depends-on "bind-key")
(depends-on "cask")
(depends-on "exec-path-from-shell")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "fuzzy")
(depends-on "helm")
(depends-on "helm-git-grep")
(depends-on "helm-gtags")
(depends-on "helm-themes")
(depends-on "highlight-symbol")
(depends-on "hlinum")
(depends-on "init-loader")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "popup")
(depends-on "popwin")
(depends-on "powerline")
(depends-on "projectile")
(depends-on "quickrun")
(depends-on "undo-tree")
(depends-on "yasnippet")
(depends-on "yatemplate")

;; Progmodes
(depends-on "cask-mode")
(depends-on "coffee-mode")
(depends-on "elixir-mode")
(depends-on "emmet-mode")
(depends-on "go-mode")
(depends-on "haskell-mode")
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "markdown-mode")
(depends-on "php-mode")
(depends-on "ruby-mode")
(depends-on "scala-mode")
(depends-on "tuareg")
(depends-on "web-mode")
(depends-on "yaml-mode")

;; JavaScript
(depends-on "indium")

;; Python
(depends-on "elpy")

;; PHP
(depends-on "ac-php")

;; Ruby
(depends-on "robe")
;(depends-on "ruby-block")
(depends-on "ruby-end")

;; Go
(depends-on "go-autocomplete")
(depends-on "go-eldoc")

;; Elixir
(depends-on "ac-alchemist")
(depends-on "alchemist")
