(source gnu)
(source melpa)

(depends-on "ac-dabbrev")
(depends-on "anzu")
(depends-on "auto-complete")
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "exec-path-from-shell")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-color-mode-line")
(depends-on "flycheck-pos-tip")
(depends-on "flycheck-tip")
(depends-on "fuzzy")
(depends-on "git-gutter-fringe+")
(depends-on "git-modes" :git "https://github.com/magit/git-modes.git")
(depends-on "helm")
(depends-on "helm-git-grep")
(depends-on "helm-gtags")
(depends-on "helm-ls-git")
(depends-on "helm-themes")
(depends-on "highlight-symbol")
(depends-on "hlinum")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "init-loader")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "popup")
(depends-on "popwin")
(depends-on "powerline")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "quickrun")
(depends-on "robe")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "smooth-scroll")
(depends-on "undo-tree")
(depends-on "use-package")
(depends-on "yasnippet")

;; progmodes
(depends-on "coffee-mode")
(depends-on "go-mode")
(depends-on "haskell-mode")
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "markdown-mode")
(depends-on "php-mode")
(depends-on "scala-mode")
(depends-on "tuareg")
(depends-on "web-mode")
(depends-on "yaml-mode")

;;; Python
(depends-on "jedi")

;;; Ruby
(depends-on "ruby-mode")
(depends-on "ruby-block")
(depends-on "ruby-end")

;;; PHP
(depends-on "php-completion"
        :git "https://github.com/suzuki/php-completion.git"
        :branch "develop"
        :files ("*.el" "phpcmp-index-of-*"))

;;; Go
(depends-on "go-autocomplete")
(depends-on "go-eldoc")

